laptops/urls.py
from django.urls import path
from . import views

app_name = 'laptops'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:program_pk>/', views.detail, name = 'detail'),
]

mypro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('laptops/', include('laptops.urls')),
]

laptops/models.py
from django.db import models

# Create your models here.
class Program(models.Model):
    name = models.CharField(max_length = 20)


class Laptop(models.Model):
    name = models.CharField(max_length = 30)
    price = models.CharField(max_length = 30)


class Graphic(models. Model):
    name = models.TextField(default='')
    programs = models.ManyToManyField(Program, related_name='graphics', blank=True)
    laptops = models.ManyToManyField(Laptop, related_name='graphics', blank=True)

    def __str__(self):
        return self.name


# class Info(models.Model):
#     laptop = models.ForeignKey(Laptop, on_delete = models.CASCADE)
#     program = models.ForeignKey(Program, on_delete = models.CASCADE)
#     graphic = models.ForeignKey(Graphic, on_delete = models.CASCADE)

laptops/views.py
from django.shortcuts import render
from .models import Program, Graphic, Laptop
from django.core.paginator import Paginator
# Create your views here.
def index(request):
    programs = Program.objects.all()

    context = {
        'programs': programs,
    }

    return render(request, 'laptops/index.html', context)
    

def detail(request, program_pk):
    # 1. Program ID를 주소로 부터 가져옴 + Program에서 pk에 해당하는 program 가져옴
    program = Program.objects.get(pk=program_pk)

    # 2. program을 돌릴 수 있는 그래픽 다 가져옴
    graphics = program.graphics.all()

    # 3. graphic이 장착된 laptop 가져오기 (for)
    laptops = []
    for graphic in graphics:
        for laptop in graphic.laptops.order_by('price'):
            laptops.append(laptop)

    context = {
        'graphics': graphics,
        'laptops': laptops,
    }

    return render(request, 'laptops/detail.html', context)

laptops/templates/laptops/detail.html
{% extends 'base.html' %}

{% block body %}

<h1> Search result </h1>

<ul>
    {% for graphic in graphics %}
        <!-- <h4>{{ graphic.name }}</h4> -->
        <!-- {% for laptop in graphic.laptops.all %}
            <li>{{ laptop.name }} - {{ laptop.price }}</li>
        {% endfor %} -->
    {% endfor%}
    {% for laptop in laptops %}
    <li>
        {{ laptop.name }} - {{ laptop.price }}
    </li>
    {% endfor %}
</ul>



<nav>
        <ul class = 'pagination'>
            {% if articles.has_revious %}
            <li class ='page-item'>
                <a href="page-ling" href= '{% url 'articles:index' %}?page={{ articles.previous_page_number }}'>Previous</a>
            </li>
            {% endif %}
    
            {% for num_page in articles.paginator.page_range %}
            <li class = 'page-item' {% if num_page == articles.number %}active{% endif %}>
                <a class = 'page-link' href= '{% url 'articles:index' %}?page= {{ num_page}}'>{{ num_page }}</a>
            </li>
            {% endfor %}
    
            {% if articles.has_next %}
            <li class = 'page-item'>
                <a class = 'page-link' href="{% url 'articles:index'%}?page={{ articles.next_page_number }}">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>










{% endblock %}

laptops/templates/laptops/index.html
{% extends 'base.html' %}

{% block body %}

<div class="alert alert-primary" role="alert">
        사용하는 프로그램을 선택하세요.
</div>

<div class="container">
    <div class = 'row'>
            <div class="col-12">사진/ 영상 편집 프로그램</div>
            {% for program in programs %}
            <div class="col-6">
            <a href="{% url 'laptops:detail' program.pk %}">{{ program.name }}</a>
            </div>
            {% endfor %}

            <div class="col-12">      </div>

            <div class="col-12">게임</div>
            <div class="col-6">
            <a href="{}">롤</a>
            </div>
            <div class="col-6">
                <a href="{}">카트라이더</a>
                </div>
                <div class="col-6">
                <a href="{}">오버워치</a>
                </div>
                <div class="col-6">
                <a href="{}">배틀그라운드</a>
                </div>


    </div>
</div>


{% endblock %}

mypro/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    {% block body %}
    {% endblock %}

    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </script>
</body>
</html>